### ISSUE TITLE
Update Title when duplicating

### ISSUE THREAD

**Issue by jinjie** [jinjie/duplicate-dataobject#1]
Add an option that that will change the title.

For example, when duplicating a DO with `Title`, will create a duplicate of the DO with title of `Title (copy)`

**Comment by wernerkrauss** [comment]
IMHO this should be solved in each DataObject class in the method `onBeforeDuplicate()`, like

```
public function onBeforeDuplicate()
{
    $this->Title .= ' (copy)';
}
```

**Comment by jinjie** [comment]
Thanks @wernerkrauss for pointing this out. Yes. I do agree that this should be done in onBeforeDuplicate()

Closing this issue.
